# Generated by Django 4.1.3 on 2022-11-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_companystaff_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliers',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
