# Generated by Django 4.1.3 on 2022-11-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_updated_suppliers_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': "Company's"},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='typecompany',
            options={'verbose_name': 'Type Company', 'verbose_name_plural': "Type Company's"},
        ),
    ]
