# Generated by Django 4.1.3 on 2022-11-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_company_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='company',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.company'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to='app.company'),
        ),
    ]
