# Generated by Django 4.1.3 on 2022-11-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_company_debt_company_level_company_supplier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyproducts',
            options={'verbose_name_plural': 'Company Products'},
        ),
        migrations.AlterModelOptions(
            name='companystaff',
            options={'verbose_name_plural': 'Company Staff'},
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='county',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='house_number',
            field=models.CharField(default=2, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompanyContacts',
        ),
    ]
