# Generated by Django 4.1.3 on 2022-11-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_companystaff_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystaff',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_staff', to='app.company'),
        ),
    ]
