# Generated by Django 4.1.3 on 2022-11-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_companystaff_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='county',
            new_name='country',
        ),
    ]
