# Generated by Django 4.1.3 on 2022-11-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_suppliersproduct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyproducts',
            unique_together={('company', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='suppliersproduct',
            unique_together={('suppler', 'product')},
        ),
    ]
