# Generated by Django 4.1.3 on 2022-11-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_companyproducts_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproducts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_company', to='app.company'),
        ),
        migrations.AlterField(
            model_name='companyproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_product', to='app.products'),
        ),
    ]
