# Generated by Django 4.1.3 on 2022-11-14 19:01
from datetime import datetime
from django.db import migrations, transaction


def create_products(apps, schema_editor):
    Products = apps.get_model('app', 'Products')
    data = [
        ['Samsung', 'S10', f'{datetime.today().strftime("%Y-%m-%d")}'],
        ['Asus', 'Y500', f'{datetime.today().strftime("%Y-%m-%d")}'],
        ['Lenovo', 'Legion', f'{datetime.today().strftime("%Y-%m-%d")}'],
        ['Microsoft', 'Windows', f'{datetime.today().strftime("%Y-%m-%d")}'],
        ['Apple', '12', f'{datetime.today().strftime("%Y-%m-%d")}'],
    ]
    for info in data:
        with transaction.atomic():
            Products.objects.create(
                name=info[0],
                model=info[1],
                release_data=info[2],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_create_typecompany'),
    ]

    operations = [
        migrations.RunPython(create_products)
    ]
