# Generated by Django 4.1.3 on 2022-11-14 19:08
from decimal import Decimal

from django.db import migrations, transaction
from random import randint

def create_company(apps, schema_editor):
    Company = apps.get_model('app', 'Company')
    TypeCompany = apps.get_model('app', 'TypeCompany')
    data = [
        ['КрасноеБелое', 'user@example.com', 'Рф', 'Москва', 'Централь', '3', 1, None],
        ['WB', 'user@example.com', 'Беларусь', 'Минск', 'Сов', '3', 1, None],
        ['Ozon', 'user@example.com', 'Рф', 'Питер', 'Централь', '3', 2, 2],
        ['Ашан', 'user@example.com', 'Польша', 'Варшава', 'Централь', '3', 3, 1],
        ['Атлант', 'user@example.com', 'Беларусь', 'Витебск', 'Централь', '3', 4, 4],
        ['KFC', 'user@example.com', 'США', 'Техас', 'Централь', '3', 5, 5],
    ]

    for info in data:
        with transaction.atomic():
            type_com = TypeCompany.objects.get(pk=info[6])
            supplier = Company.objects.filter(pk=info[7]).first()
            Company.objects.create(
                name=info[0],
                type_company=type_com,
                email=info[1],
                country=info[2].lower(),
                city=info[3].lower(),
                street=info[4].lower(),
                house_number=info[5],
                supplier=supplier,
                debt=Decimal(randint(0, 100))
            )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_create_product'),
    ]

    operations = [
        migrations.RunPython(create_company)
    ]
