# Generated by Django 4.1.3 on 2022-11-14 19:38

from django.db import migrations, transaction
from decimal import Decimal


def create(apps, schema_editor):
    Company = apps.get_model('app', 'Company')
    Suppliers = apps.get_model('app', 'Suppliers')

    data = [
        [1, 4, Decimal(55.50)],
        [2, 3, Decimal(25.50)],
        [4, 5, Decimal(70.80)],
        [5, 6, Decimal(155.50)],
    ]

    for info in data:
        with transaction.atomic():
            provider = Company.objects.get(pk=info[0])
            seller = Company.objects.get(pk=info[1])
            Suppliers.objects.create(
                provider=provider,
                seller=seller,
                price=info[2],
            )

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_create_company'),
    ]

    operations = [
        migrations.RunPython(create)
    ]
