# Generated by Django 4.1.3 on 2022-11-14 19:51

from django.db import migrations, transaction


def create(apps, schema_editor):
    Company = apps.get_model('app', 'Company')
    Products = apps.get_model('app', 'Products')
    CompanyProducts = apps.get_model('app', 'CompanyProducts')
    data = [
        [1, [4, 5]],
        [2, [1, 2]],
        [3, [1]],
        [4, [4, 5]],
        [5, [4]],
        [6, [4]]
    ]

    for info in data:
        with transaction.atomic():
            company = Company.objects.get(pk=info[0])
            for i in info[1]:
                product = Products.objects.get(pk=i)
                CompanyProducts.objects.create(
                    company=company,
                    product=product,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_create_suppliers'),
    ]

    operations = [
        migrations.RunPython(create)
    ]
