# Generated by Django 4.1.3 on 2022-11-14 20:02

from django.db import migrations, transaction


def create(apps, schema_editor):
    SuppliersProduct = apps.get_model('app', 'SuppliersProduct')
    Products = apps.get_model('app', 'Products')
    Suppliers = apps.get_model('app', 'Suppliers')
    data = [
        [1, [4, 5]],
        [2, [1, 2]],
        [3, [4]],
        [4, [4]],
    ]

    for info in data:
        with transaction.atomic():
            company = Suppliers.objects.get(pk=info[0])
            for i in info[1]:
                product = Products.objects.get(pk=i)
                SuppliersProduct.objects.create(
                    suppler=company,
                    product=product,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_create_company_products'),
    ]

    operations = [
        migrations.RunPython(create)
    ]
