# Generated by Django 4.1.3 on 2022-11-14 20:13

from django.db import migrations, transaction


def create(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    CompanyStaff = apps.get_model('app', 'CompanyStaff')
    Company = apps.get_model('app', 'Company')
    data = [
        ['user1', 'user1@example.com', 'Qwert1357'],
        ['user2', 'user2@example.com', 'Qwert1357'],
    ]

    for info in data:
        with transaction.atomic():

            User.objects.create(
                username=info[0],
                email=info[1],
                password=info[2],
            )
    data = [
        [1, [1]],
        [2, [2]],
        [3, [1, 2]],
    ]
    for info in data:
        with transaction.atomic():
            company = Company.objects.get(pk=info[0])
            for i in info[1]:
                staff = User.objects.get(pk=i)
                CompanyStaff.objects.create(
                    company=company,
                    staff=staff,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_create_suppliers_product'),
    ]

    operations = [
        migrations.RunPython(create)
    ]
